---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: help-desk
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "hpa"]
  verbs: ["get", "list", "watch", "create", "describe"] # You can also use ["*"]
