# A role is a definition of the permissions for each Kubernetes resource type
# This example is basically readonly for everything
#
# A ClusteRole differs from a Role in that it applies to the entire cluster, thus there 
# is not namespace defined. This example is a ClusterRole
#  
# User Impersonation with kubectl is a good way to test RBAC
# https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation
# kubectl auth can-i get pods --as help-desk
# kubectl auth can-i delete pods --as help-desk
# 
# kubectl describe role help-desk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  # The view role was renamed to help-desk and modified, to create this new cluster role
  # First we obtained the view object by kubectl get clusterrole view -o yaml >help-desk-cluster-role.yaml
  name: help-desk
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  # This was added to the built in View role
  - describe

