# A role is a definition of the permissions for each Kubernetes resource type
# This example is basically readonly for deployments, repicases, pods, 
# and horizontal pod autoscalers
#
# User Impersonation with kubectl is a good way to test RBAC
# https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation
# this is wrong:
# kubectl get pods --as=help-desk --as-group=system:masters
# 
# kubectl describe role help-desk
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: help-desk
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "hpa"]
  verbs: ["get", "list", "watch", "describe"] # You can also use ["*"]
