---
# Note a ClusterRoleBinding is cluster-wide
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: help-desk-binding
subjects:
- kind: User
  name: help-desk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: help-desk
  apiGroup: rbac.authorization.k8s.io
